#!/usr/bin/env python3
"""
Simple Serpens Catalog Creator

Creates a functional Serpens catalog by using source positions
and extracting properties from column density map using a more robust method.

Author: ASTRA Discovery System
Date: 5 April 2026
"""

import numpy as np
from astropy.io import fits
from astropy.wcs import WCS
import os

HGBS_DIR = '/Users/gjw255/astrodata/SWARM/ASTRA/HGBS_SERPENS'
OBSERVED_CAT = os.path.join(HGBS_DIR, 'HGBS_serpens_observed_core_catalog.txt')
COL_DEN_FILE = os.path.join(HGBS_DIR, 'HGBS_serpens_hires_column_density_map.fits')
OUTPUT_CAT = os.path.join(HGBS_DIR, 'core_catalog_serpens_derived.csv')

DISTANCE_PC = 260.0
MIN_NH2 = 1e21  # Minimum column density to consider

print("="*70)
print("Creating Serpens Derived Catalog")
print("="*70)

# Load column density map
print(f"\nLoading column density map...")
with fits.open(COL_DEN_FILE) as hdul:
    col_data = hdul[0].data
    col_header = hdul[0].header
    wcs = WCS(col_header)

print(f"  Data shape: {col_data.shape}")

# Get pixel scale
cdelt1 = np.abs(col_header.get('CDELT1', 5.0/3600))
pixel_scale_rad = cdelt1 * np.pi / 180
pixel_scale_pc = DISTANCE_PC * pixel_scale_rad
CM_PER_PC = 3.086e18

print(f"  Pixel scale: {pixel_scale_pc:.4f} pc")

# Constants
H2_MASS_G = 2.8 * 1.673e-24
MSUN_G = 1.989e33

# Simple source detection using percentile threshold
print(f"\nDetecting cores from column density map...")
col_data_clean = np.nan_to_num(col_data, nan=0.0, posinf=0.0, neginf=0.0)

# Use 90th percentile as threshold (similar to other regions)
threshold = np.percentile(col_data_clean[col_data_clean > MIN_NH2], 90)
print(f"  Detection threshold: {threshold/1e21:.2f} × 10^21 cm^-2")

# Binary mask
binary_mask = col_data_clean > threshold

# Connected component analysis to identify individual cores
from scipy.ndimage import label

labeled_mask, num_features = label(binary_mask)
print(f"  Found {num_features} potential cores")

# Extract properties for each core
cores = []

min_size = 10  # minimum pixels for a core
for i in range(1, num_features + 1):
    core_mask = labeled_mask == i
    npix = np.sum(core_mask)

    if npix < min_size:
        continue

    # Get peak position
    y_coords, x_coords = np.where(core_mask)

    # Use the position of maximum column density as the core center
    max_idx = np.argmax(col_data_clean[core_mask])
    py = y_coords[max_idx]
    px = x_coords[max_idx]

    # Peak column density
    peak_nh2 = col_data_clean[py, px]

    # Mean column density
    mean_nh2 = np.mean(col_data_clean[core_mask])

    # Estimate mass from column density
    # Mass = N_H2 × area × mass_per_H2
    area_cm2 = npix * (pixel_scale_pc * CM_PER_PC) ** 2
    mass_g = peak_nh2 * area_cm2 * H2_MASS_G
    mass_msun = mass_g / MSUN_G

    # Get position
    try:
        coord = wcs.pixel_to_world(px, py)
        ra_deg = coord.ra.deg
        dec_deg = coord.dec.deg

        # Create RA/Dec strings
        ra_hours = ra_deg / 15.0
        ra_h = int(ra_hours)
        ra_m = int((ra_hours - ra_h) * 60)
        ra_s = (ra_hours - ra_h - ra_m/60.0) * 3600
        ra_str = f"{ra_h:02d}:{ra_m:02d}:{ra_s:06.3f}"

        dec_str = f"{dec_deg:+.6f}"

        # Classify based on density and mass
        if mean_nh2 < 5e21:
            core_type = 'starless'
            temp = 15.0
        elif mean_nh2 < 1.5e22:
            core_type = 'prestellar' if mass_msun > 0.3 else 'starless'
            temp = 12.0 if core_type == 'prestellar' else 14.0
        else:
            core_type = 'prestellar'
            temp = 11.0

        cores.append({
            'id': i,
            'name': f'SERPENS_{i:04d}',
            'ra': ra_str,
            'dec': dec_str,
            'ra_deg': ra_deg,
            'dec_deg': dec_deg,
            'mass': mass_msun,
            'temp': temp,
            'nh2_peak': peak_nh2 / 1e21,
            'npix': npix,
            'alpha_be': None,
            'type': core_type
        })

    except Exception as e:
        continue

print(f"  Successfully extracted {len(cores)} cores")

# Save catalog
print(f"\nSaving catalog to: {OUTPUT_CAT}")
with open(OUTPUT_CAT, 'w') as f:
    f.write("# Serpens Derived Core Catalog\n")
    f.write("# Generated by ASTRA Discovery System\n")
    f.write(f"# Distance: {DISTANCE_PC} pc\n")
    f.write("# Method: Source detection from column density map\n")
    f.write("# Columns: obj_id, mass_Msun, peak_N_cm2, npix, ra_deg, dec_deg, Tdust_K, type\n")
    for core in cores:
        f.write(f"{core['id']},{core['mass']:.4f},{core['nh2_peak']*1e21:.2e},{core['npix']},{core['ra_deg']:.6f},{core['dec_deg']:.6f},{core['temp']:.2f},{core['type']}\n")

# Statistics
print("\n" + "="*70)
print("SERPENS DERIVED CATALOG STATISTICS")
print("="*70)

if cores:
    masses = [c['mass'] for c in cores if c['mass'] > 0]
    temps = [c['temp'] for c in cores]

    types = {}
    for core in cores:
        ctype = core['type']
        types[ctype] = types.get(ctype, 0) + 1

    print(f"\nTotal cores: {len(cores)}")

    if masses:
        print(f"\nMass statistics [Msun]:")
        print(f"  Range: {np.min(masses):.4f} - {np.max(masses):.4f}")
        print(f"  Median: {np.median(masses):.4f}")

    if temps:
        print(f"\nTemperature statistics [K]:")
        print(f"  Range: {np.min(temps):.2f} - {np.max(temps):.2f}")
        print(f"  Median: {np.median(temps):.2f}")

    print(f"\nCore type distribution:")
    for ctype, count in sorted(types.items()):
        print(f"  {ctype}: {count} ({100*count/len(cores):.1f}%)")

    # Count massive cores
    massive = sum(1 for c in cores if c['mass'] > 5.0)
    print(f"\nMassive cores (>5 Msun): {massive} ({100*massive/len(cores):.1f}%)")

    prestellar_pct = 100 * types.get('prestellar', 0) / len(cores)
    print(f"\nPrestellar fraction: {prestellar_pct:.1f}%")

print("\n" + "="*70)
print("CATALOG CREATION COMPLETE")
print("="*70)
