"""
Neural-Symbolic Theorem Prover for STAN V40

Combines:
- LLM-generated proof sketches
- Symbolic verification
- Counterexample search
- Proof repair

Target: +20-25% on mathematical proofs

Date: 2025-12-11
Version: 40.0
"""

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Tuple, Set, Callable
from enum import Enum


class TheoremStatus(Enum):
    """Status of a theorem"""
    CONJECTURED = "conjectured"
    PROVING = "proving"
    PROVED = "proved"
    DISPROVED = "disproved"
    UNKNOWN = "unknown"
    TIMEOUT = "timeout"


class ProofMethod(Enum):
    """Methods for proving theorems"""
    DIRECT = "direct"
    CONTRADICTION = "contradiction"
    INDUCTION = "induction"
    CONSTRUCTION = "construction"
    CASES = "cases"
    COUNTEREXAMPLE = "counterexample"


@dataclass
class ProofSketchStep:
    """A step in a proof sketch"""
    step_id: str
    statement: str
    justification: str
    proof_method: Optional[ProofMethod] = None
    dependencies: List[str] = field(default_factory=list)

    # Verification
    verified: bool = False
    verification_score: float = 0.0
    issues: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict:
        return {
            'id': self.step_id,
            'statement': self.statement,
            'justification': self.justification,
            'verified': self.verified,
            'score': self.verification_score
        }


@dataclass
class ProofSketch:
    """A proof sketch generated by LLM"""
    theorem: str
    method: ProofMethod
    steps: List[ProofSketchStep]

    # Overall assessment
    complete: bool = False
    confidence: float = 0.0
    gaps: List[str] = field(default_factory=list)

    # Metadata
    source: str = "llm"
    iterations: int = 0

    def to_dict(self) -> Dict:
        return {
            'theorem': self.theorem,
            'method': self.method.value,
            'steps': [s.to_dict() for s in self.steps],
            'complete': self.complete,
            'confidence': self.confidence,
            'gaps': self.gaps
        }


@dataclass
class Counterexample:
    """A counterexample disproving a statement"""
    statement: str
    variable_assignment: Dict[str, Any]
    explanation: str = ""

    def to_dict(self) -> Dict:
        return {
            'statement': self.statement,
            'assignment': self.variable_assignment,
            'explanation': self.explanation
        }


class ProofVerifier:
    """
    Verifies proof steps symbolically.

    Checks:
    - Logical validity
    - Correct rule application
    - No missing steps
    - Proper dependencies
    """

    def __init__(self):
        # Known proof rules
        self.inference_rules = {
            'modus_ponens': self._verify_modus_ponens,
            'modus_tollens': self._verify_modus_tollens,
            'hypothetical_syllogism': self._verify_hypothetical_syllogism,
            'disjunctive_syllogism': self._verify_disjunctive_syllogism,
            'addition': self._verify_addition,
            'simplification': self._verify_simplification,
            'conjunction': self._verify_conjunction,
            'universal_instantiation': self._verify_universal_instantiation,
            'algebraic_manipulation': self._verify_algebraic,
            'substitution': self._verify_substitution,
        }

        self.verifications_performed = 0

    def verify_step(self, step: ProofSketchStep,
                   context: Dict[str, Any]) -> Tuple[bool, float, List[str]]:
        """
        Verify a single proof step.

        Args:
            step: The step to verify
            context: Previous steps and known facts

        Returns:
            (valid, confidence, issues)
        """
        self.verifications_performed += 1
        issues = []

        # Check justification matches known rules
        justification_lower = step.justification.lower()

        for rule_name, verifier in self.inference_rules.items():
            if rule_name.replace('_', ' ') in justification_lower:
                valid, conf = verifier(step, context)
                if not valid:
                    issues.append(f"Rule '{rule_name}' not properly applied")
                return valid, conf, issues

        # Default verification - check dependencies exist
        for dep in step.dependencies:
            if dep not in context.get('proven_steps', {}):
                issues.append(f"Dependency '{dep}' not proven")
                return False, 0.0, issues

        # Heuristic verification based on statement structure
        confidence = self._heuristic_verification(step, context)

        return confidence > 0.5, confidence, issues

    def verify_proof(self, sketch: ProofSketch) -> Tuple[bool, Dict]:
        """
        Verify a complete proof sketch.

        Returns:
            (all_valid, verification_report)
        """
        context = {'proven_steps': {}, 'assumptions': []}
        all_valid = True
        report = {'steps': [], 'gaps': [], 'score': 0.0}

        for step in sketch.steps:
            valid, conf, issues = self.verify_step(step, context)

            step.verified = valid
            step.verification_score = conf
            step.issues = issues

            report['steps'].append({
                'id': step.step_id,
                'valid': valid,
                'confidence': conf,
                'issues': issues
            })

            if valid:
                context['proven_steps'][step.step_id] = step.statement
            else:
                all_valid = False
                report['gaps'].append(step.step_id)

        # Overall score
        if sketch.steps:
            report['score'] = sum(s.verification_score for s in sketch.steps) / len(sketch.steps)

        return all_valid, report

    def _verify_modus_ponens(self, step: ProofSketchStep,
                            context: Dict) -> Tuple[bool, float]:
        """Verify: P, P->Q |- Q"""
        proven = context.get('proven_steps', {})

        # Look for P and P->Q in dependencies
        for dep_id in step.dependencies:
            dep_stmt = proven.get(dep_id, "")
            if '->' in dep_stmt or 'implies' in dep_stmt.lower():
                # Found implication
                return True, 0.8

        return False, 0.3

    def _verify_modus_tollens(self, step: ProofSketchStep,
                             context: Dict) -> Tuple[bool, float]:
        """Verify: P->Q, ~Q |- ~P"""
        proven = context.get('proven_steps', {})

        has_implication = any('->' in proven.get(d, '') for d in step.dependencies)
        has_negation = any('not' in proven.get(d, '').lower() for d in step.dependencies)

        if has_implication and has_negation:
            return True, 0.8
        return False, 0.3

    def _verify_hypothetical_syllogism(self, step: ProofSketchStep,
                                       context: Dict) -> Tuple[bool, float]:
        """Verify: P->Q, Q->R |- P->R"""
        proven = context.get('proven_steps', {})

        implications = [d for d in step.dependencies
                       if '->' in proven.get(d, '')]
        if len(implications) >= 2:
            return True, 0.8
        return False, 0.3

    def _verify_disjunctive_syllogism(self, step: ProofSketchStep,
                                      context: Dict) -> Tuple[bool, float]:
        """Verify: P v Q, ~P |- Q"""
        proven = context.get('proven_steps', {})

        has_disjunction = any(' or ' in proven.get(d, '').lower() for d in step.dependencies)
        has_negation = any('not' in proven.get(d, '').lower() for d in step.dependencies)

        if has_disjunction and has_negation:
            return True, 0.8
        return False, 0.3

    def _verify_addition(self, step: ProofSketchStep,
                        context: Dict) -> Tuple[bool, float]:
        """Verify: P |- P v Q"""
        if ' or ' in step.statement.lower():
            return True, 0.9
        return False, 0.3

    def _verify_simplification(self, step: ProofSketchStep,
                              context: Dict) -> Tuple[bool, float]:
        """Verify: P ^ Q |- P"""
        proven = context.get('proven_steps', {})

        for dep_id in step.dependencies:
            dep_stmt = proven.get(dep_id, "")
            if ' and ' in dep_stmt.lower():
                return True, 0.9
        return False, 0.3

    def _verify_conjunction(self, step: ProofSketchStep,
                           context: Dict) -> Tuple[bool, float]:
        """Verify: P, Q |- P ^ Q"""
        if ' and ' in step.statement.lower() and len(step.dependencies) >= 2:
            return True, 0.9
        return False, 0.3

    def _verify_universal_instantiation(self, step: ProofSketchStep,
                                        context: Dict) -> Tuple[bool, float]:
        """Verify: ForAll x. P(x) |- P(a)"""
        proven = context.get('proven_steps', {})

        for dep_id in step.dependencies:
            dep_stmt = proven.get(dep_id, "")
            if 'for all' in dep_stmt.lower() or 'forall' in dep_stmt.lower():
                return True, 0.85
        return False, 0.3

    def _verify_algebraic(self, step: ProofSketchStep,
                         context: Dict) -> Tuple[bool, float]:
        """Verify algebraic manipulation"""
        # Simple heuristic: check if step involves equations
        if '=' in step.statement:
            return True, 0.7
        return True, 0.5

    def _verify_substitution(self, step: ProofSketchStep,
                            context: Dict) -> Tuple[bool, float]:
        """Verify substitution"""
        # Check if justification mentions what was substituted
        if 'substitut' in step.justification.lower():
            return True, 0.75
        return False, 0.3

    def _heuristic_verification(self, step: ProofSketchStep,
                               context: Dict) -> float:
        """Heuristic verification based on structure"""
        score = 0.5  # Base

        # Has justification
        if step.justification:
            score += 0.1

        # References dependencies
        if step.dependencies:
            score += 0.1

        # Statement is well-formed
        if len(step.statement) > 5:
            score += 0.1

        return min(1.0, score)


class CounterexampleSearch:
    """
    Searches for counterexamples to disprove statements.

    Uses:
    - Random testing
    - Boundary values
    - Constraint-guided search
    """

    def __init__(self, max_attempts: int = 1000):
        self.max_attempts = max_attempts
        self.searches_performed = 0
        self.counterexamples_found = 0

    def search(self, statement: str,
              variables: Dict[str, str] = None,
              domain: Dict[str, Tuple[float, float]] = None) -> Optional[Counterexample]:
        """
        Search for counterexample to statement.

        Args:
            statement: Statement to disprove
            variables: Variable name -> type
            domain: Variable name -> (min, max) for numeric types

        Returns:
            Counterexample if found, None otherwise
        """
        self.searches_performed += 1
        variables = variables or {}
        domain = domain or {}

        # Extract variables from statement
        extracted = re.findall(r'\b([a-zA-Z_][a-zA-Z0-9_]*)\b', statement)
        for var in extracted:
            if var not in variables and not var[0].isupper():
                variables[var] = 'Real'

        # Default domains
        for var in variables:
            if var not in domain:
                domain[var] = (-100.0, 100.0)

        # Try boundary values first
        counter = self._try_boundary_values(statement, variables, domain)
        if counter:
            self.counterexamples_found += 1
            return counter

        # Try random values
        counter = self._try_random_values(statement, variables, domain)
        if counter:
            self.counterexamples_found += 1
            return counter

        return None

    def _try_boundary_values(self, statement: str,
                            variables: Dict[str, str],
                            domain: Dict[str, Tuple]) -> Optional[Counterexample]:
        """Try boundary values"""
        boundary_values = [0, 1, -1, 0.5, -0.5]

        for var in variables:
            min_val, max_val = domain.get(var, (-100, 100))
            boundary_values.extend([min_val, max_val, (min_val + max_val) / 2])

        # Try combinations
        import itertools

        var_list = list(variables.keys())
        for values in itertools.product(boundary_values, repeat=min(len(var_list), 3)):
            assignment = {var_list[i]: values[i] for i in range(min(len(var_list), len(values)))}

            if not self._evaluate_statement(statement, assignment):
                return Counterexample(
                    statement=statement,
                    variable_assignment=assignment,
                    explanation="Statement false for boundary values"
                )

        return None

    def _try_random_values(self, statement: str,
                          variables: Dict[str, str],
                          domain: Dict[str, Tuple]) -> Optional[Counterexample]:
        """Try random values"""
        import random

        for _ in range(min(self.max_attempts, 100)):
            assignment = {}
            for var, var_type in variables.items():
                min_val, max_val = domain.get(var, (-100, 100))
                if var_type == 'Int':
                    assignment[var] = random.randint(int(min_val), int(max_val))
                else:
                    assignment[var] = random.uniform(min_val, max_val)

            if not self._evaluate_statement(statement, assignment):
                return Counterexample(
                    statement=statement,
                    variable_assignment=assignment,
                    explanation="Statement false for random assignment"
                )


class NeuralTheoremProver:
    """
    Neural-symbolic theorem prover (restored 2026-08-21).

    Imported by v40_system but never defined in the original module
    (2026-08-21 audit). This honest restoration only decides claims it
    can soundly check:

    - ``lhs = rhs`` where both sides are pure arithmetic expressions
      (numbers, + - * / **, parentheses) -> PROVED / DISPROVED by
      direct evaluation of both sides over a whitelisted AST.
    - Anything else -> (TheoremStatus.UNKNOWN, None).

    It never fabricates a proof or a counterexample: undecided means
    undecided.
    """

    def __init__(self):
        import ast as _ast  # local: safe-evaluation only, no import cost otherwise

        self._ast = _ast
        self.verifier = ProofVerifier()
        self.counterexample_search = CounterexampleSearch()

        # Statistics
        self.theorems_attempted = 0
        self.proved_count = 0
        self.disproved_count = 0
        self.undecided_count = 0

    # ------------------------------------------------------------ public

    def prove(self, theorem: str) -> Tuple[TheoremStatus, Any]:
        """
        Attempt to prove or disprove a theorem.

        Returns:
            (status, result) where result is a ProofSketch when PROVED,
            a Counterexample when DISPROVED, and None when UNKNOWN.
        """
        self.theorems_attempted += 1

        if not theorem or not isinstance(theorem, str):
            self.undecided_count += 1
            return TheoremStatus.UNKNOWN, None

        # Only "=" claims over pure arithmetic are soundly decidable here.
        if "=" not in theorem or "!=" in theorem:
            self.undecided_count += 1
            return TheoremStatus.UNKNOWN, None

        lhs_text, rhs_text = theorem.split("=", 1)
        lhs = self._safe_eval(lhs_text)
        rhs = self._safe_eval(rhs_text)

        if lhs is None or rhs is None:
            # Not pure arithmetic (or division by zero): do not guess.
            self.undecided_count += 1
            return TheoremStatus.UNKNOWN, None

        if self._nearly_equal(lhs, rhs):
            self.proved_count += 1
            return TheoremStatus.PROVED, self._arithmetic_proof(
                theorem, lhs, rhs)

        self.disproved_count += 1
        return TheoremStatus.DISPROVED, Counterexample(
            statement=theorem,
            variable_assignment={'lhs': lhs, 'rhs': rhs},
            explanation=(f"Direct evaluation: left side is {lhs}, "
                         f"right side is {rhs}")
        )

    def get_stats(self) -> Dict[str, Any]:
        """Prover statistics"""
        return {
            'theorems_attempted': self.theorems_attempted,
            'proved': self.proved_count,
            'disproved': self.disproved_count,
            'undecided': self.undecided_count
        }

    # ----------------------------------------------------------- private

    def _arithmetic_proof(self, theorem: str,
                          lhs: float, rhs: float) -> ProofSketch:
        """Build a proof sketch for a verified arithmetic equality"""
        step = ProofSketchStep(
            step_id="1",
            statement=theorem,
            justification=(f"Direct computation: {lhs} = {rhs} "
                           f"(whitelisted-AST evaluation of both sides)"),
            proof_method=ProofMethod.DIRECT,
            verified=True,
            verification_score=1.0
        )
        return ProofSketch(
            theorem=theorem,
            method=ProofMethod.DIRECT,
            steps=[step],
            complete=True,
            confidence=1.0,
            source="arithmetic_evaluation"
        )

    def _safe_eval(self, text: str) -> Optional[float]:
        """
        Evaluate a pure-arithmetic expression via a whitelisted AST.

        Returns None if the text contains anything other than numeric
        literals, + - * / **, unary +/-, or parentheses.
        """
        text = text.strip()
        if not text:
            return None

        try:
            tree = self._ast.parse(text, mode="eval")
        except (SyntaxError, ValueError):
            return None

        return self._eval_node(tree.body)

    def _eval_node(self, node) -> Optional[float]:
        """Recursively evaluate a whitelisted AST node; None = not pure"""
        ast = self._ast

        if isinstance(node, ast.Constant):
            if isinstance(node.value, (int, float)) and not isinstance(
                    node.value, bool):
                return float(node.value)
            return None

        if isinstance(node, ast.BinOp) and isinstance(
                node.op, (ast.Add, ast.Sub, ast.Mult, ast.Div, ast.Pow)):
            left = self._eval_node(node.left)
            right = self._eval_node(node.right)
            if left is None or right is None:
                return None
            try:
                if isinstance(node.op, ast.Add):
                    return left + right
                if isinstance(node.op, ast.Sub):
                    return left - right
                if isinstance(node.op, ast.Mult):
                    return left * right
                if isinstance(node.op, ast.Div):
                    return left / right
                # Pow: keep magnitudes sane so crafted inputs cannot hang us
                if abs(right) > 100 or abs(left) > 1e6:
                    return None
                return left ** right
            except (ZeroDivisionError, OverflowError):
                return None

        if isinstance(node, ast.UnaryOp) and isinstance(
                node.op, (ast.UAdd, ast.USub)):
            value = self._eval_node(node.operand)
            if value is None:
                return None
            return value if isinstance(node.op, ast.UAdd) else -value

        return None

    @staticmethod
    def _nearly_equal(a: float, b: float,
                      rel_tol: float = 1e-9, abs_tol: float = 1e-12) -> bool:
        """Float comparison with tolerance"""
        return abs(a - b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)
