#!/usr/bin/env python3
"""
generate_turbulent_campaign.py
Generate Athena++ input files for Turbulent Amplitude Gap Campaign

Usage:
    python generate_turbulent_campaign.py <output_directory>
"""

import os
import json
import argparse

# Parameter space definition
TURBULENT_AMPLITUDES = [1.0, 1.5, 2.0, 2.5, 3.0]
LINE_MASS_FRACTIONS = [1.0, 1.2, 1.5, 2.0]
PLASMA_BETA_VALUES = [0.3, 0.5, 1.0, 2.0]
FIELD_GEOMETRIES = [0, 90]  # degrees
RANDOM_SEEDS = [1, 2, 3, 4, 5]

# Athena++ configuration template
ATHENA_TEMPLATE = """
# Turbulent Amplitude Gap Campaign Configuration
# Parameter point: {param_string}
# Generated by: generate_turbulent_campaign.py

<parthenon>
fcons = conservative
tlim = {tlim}
nlim = 100000000
restart = false
output_par = false

<mesh>
nx1 = {nx1}
nx2 = {nx2}
nx3 = {nx3}
flevels = 1
refinement = static
nbc = {nbc}
ncycle_out = {ncycle_out}

<coordinates>
x1min = {x1min}
x1max = {x1max}
x2min = {x2min}
x2max = {x2max}
x3min = {x3min}
x3max = {x3max}
x1grid = {x1grid}
x2grid = {x2grid}
x3grid = {x3grid}

<hydro>
eos = isothermal
c_s = 1.0
gamma = 1.001
fixed_idegas = false

<field>
f = {field_f}
b_initial = {b_initial}
b_initial_type = uniform

<filament>
rho0 = 1.0
W = 0.3
f_line_mass = {f_line_mass}
beta = {beta}
theta_B = {theta_B}
profile = gaussian

<turbulence>
amplitude = {turb_amplitude}
spectrum = kolmogorov
n_modes = 8
coherent = true
seed = {seed}

<gravity>
four_pi_G = {four_pi_G}
solver = fft

<output>
fntype = hst
dt = {hst_dt}
variable = prim, cons
fntype = tab
dt = {tab_dt}
fntype = hdf5
dt = {hdf5_dt}
variable = prim, cons
sum_x2 = true
sum_x3 = true

<time>
start_first = 0.0
cfl_number = 0.3
nlim = {nlim}
"""

def calculate_B_field(beta, rho0=1.0, cs=1.0):
    """
    Calculate magnetic field strength from plasma beta.

    B = sqrt(8*pi*rho*cs^2 / beta)
    """
    import math
    return math.sqrt(8.0 * math.pi * rho0 * cs**2 / beta)

def generate_parameter_string(f, beta, theta, seed):
    """Generate unique parameter identifier string."""
    return f"f{f}_b{beta}_t{theta}_s{seed}"

def create_athena_input_file(output_dir, f, beta, theta, turb_amp, seed):
    """Create one Athena++ input file."""
    param_string = generate_parameter_string(f, beta, theta, seed)
    sim_dir = os.path.join(output_dir, param_string)
    os.makedirs(sim_dir, exist_ok=True)

    # Calculate B field from beta
    B_field = calculate_B_field(beta)

    # Fill template
    config_content = ATHENA_TEMPLATE.format(
        param_string=param_string,
        tlim=2.0,  # 2 tJ
        nx1=512,
        nx2=64,
        nx3=64,
        nbc=2,
        ncycle_out=1,
        x1min=0.0,
        x1max=16.0,  # 16 λJ
        x2min=-1.0,
        x2max=1.0,   # 2 λJ
        x3min=-0.5,
        x3max=0.5,   # 1 λJ
        x1grid="uniform",
        x2grid="uniform",
        x3grid="uniform",
        field_f=0.0,
        b_initial=B_field,
        b_initial_type="uniform",
        f_line_mass=f,
        beta=beta,
        theta_B=theta,
        turb_amplitude=turb_amp,
        seed=seed,
        four_pi_G=4.0 * 3.14159265359**2,  # λJ = 1
        hst_dt=0.001,  # History files
        tab_dt=0.01,   # Tab files
        hdf5_dt=0.01,  # HDF5 snapshots (fine temporal resolution)
        nlim=100000000
    )

    # Write input file
    input_file = os.path.join(sim_dir, 'athena_input.txt')
    with open(input_file, 'w') as f_out:
        f_out.write(config_content)

    return sim_dir

def generate_campaign_metadata(output_dir):
    """Generate metadata file for campaign tracking."""
    metadata = {
        'campaign_name': 'Turbulent_Amplitude_Gap',
        'version': '1.0',
        'creation_date': '2026-05-28',
        'total_simulations': len(TURBULENT_AMPLITUDES) *
                             len(LINE_MASS_FRACTIONS) *
                             len(PLASMA_BETA_VALUES) *
                             len(FIELD_GEOMETRIES) *
                             len(RANDOM_SEEDS),
        'parameter_space': {
            'turbulent_amplitudes': TURBULENT_AMPLITUDES,
            'line_mass_fractions': LINE_MASS_FRACTIONS,
            'plasma_beta_values': PLASMA_BETA_VALUES,
            'field_geometries': FIELD_GEOMETRIES,
            'random_seeds': RANDOM_SEEDS
        },
        'simulation_config': {
            'domain_size': [16.0, 2.0, 1.0],  # λJ units
            'resolution': [512, 64, 64],
            'tlim': 2.0,  # tJ units
            'hdf5_interval': 0.01,  # tJ units
            'turbulence_n_modes': 8,
            'turbulence_coherent': True
        },
        'analysis_pipeline': {
            'detection_threshold': 2e-4,
            'min_peak_separation': 0.5,  # λJ
            'min_peak_height': 1.5,  # × ambient density
            'bootstrap_iterations': 10000
        }
    }

    metadata_file = os.path.join(output_dir, 'campaign_metadata.json')
    with open(metadata_file, 'w') as f:
        json.dump(metadata, f, indent=2)

def main():
    parser = argparse.ArgumentParser(
        description='Generate Athena++ input files for Turbulent Amplitude Gap Campaign'
    )
    parser.add_argument(
        'output_dir',
        type=str,
        help='Root directory for campaign configuration files'
    )

    args = parser.parse_args()

    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)

    print(f"Generating Turbulent Amplitude Gap Campaign configurations")
    print(f"Output directory: {args.output_dir}")
    print(f"Total simulations: {len(TURBULENT_AMPLITUDES) * len(LINE_MASS_FRACTIONS) * len(PLASMA_BETA_VALUES) * len(FIELD_GEOMETRIES) * len(RANDOM_SEEDS)}")
    print()

    simulation_dirs = []
    sim_count = 0

    # Generate all parameter combinations
    for f in LINE_MASS_FRACTIONS:
        for beta in PLASMA_BETA_VALUES:
            for theta in FIELD_GEOMETRIES:
                for turb_amp in TURBULENT_AMPLITUDES:
                    for seed in RANDOM_SEEDS:
                        sim_dir = create_athena_input_file(
                            args.output_dir,
                            f, beta, theta, turb_amp, seed
                        )
                        simulation_dirs.append(sim_dir)
                        sim_count += 1

                        if sim_count % 100 == 0:
                            print(f"Generated {sim_count} configuration files...")

    # Generate metadata
    generate_campaign_metadata(args.output_dir)

    # Create simulation list file for batch submission
    list_file = os.path.join(args.output_dir, 'simulation_list.txt')
    with open(list_file, 'w') as f:
        for sim_dir in simulation_dirs:
            f.write(f"{sim_dir}\n")

    print(f"\nCampaign configuration complete!")
    print(f"  - Configuration files: {sim_count}")
    print(f"  - Metadata: {args.output_dir}/campaign_metadata.json")
    print(f"  - Simulation list: {list_file}")

if __name__ == '__main__':
    main()
